// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGtGXLMsJunf4ovVHoYYWphNSYDdCi02Q',
    appId: '1:201676927679:web:ebb0e42feeec46a52fcc0a',
    messagingSenderId: '201676927679',
    projectId: 'mike-split',
    authDomain: 'mike-split.firebaseapp.com',
    storageBucket: 'mike-split.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXVABZBLPHWl55OAKVVutVslZ4EHk-1U4',
    appId: '1:201676927679:android:76cc1cbe72b820e82fcc0a',
    messagingSenderId: '201676927679',
    projectId: 'mike-split',
    storageBucket: 'mike-split.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQTbE4aYa0TV1N4ogqAqYiaQmk_6rbn28',
    appId: '1:201676927679:ios:0164de409a3f46202fcc0a',
    messagingSenderId: '201676927679',
    projectId: 'mike-split',
    storageBucket: 'mike-split.firebasestorage.app',
    iosBundleId: 'com.example.jfkGuys',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQTbE4aYa0TV1N4ogqAqYiaQmk_6rbn28',
    appId: '1:201676927679:ios:0164de409a3f46202fcc0a',
    messagingSenderId: '201676927679',
    projectId: 'mike-split',
    storageBucket: 'mike-split.firebasestorage.app',
    iosBundleId: 'com.example.jfkGuys',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGtGXLMsJunf4ovVHoYYWphNSYDdCi02Q',
    appId: '1:201676927679:web:26fe7a1126ecf86b2fcc0a',
    messagingSenderId: '201676927679',
    projectId: 'mike-split',
    authDomain: 'mike-split.firebaseapp.com',
    storageBucket: 'mike-split.firebasestorage.app',
  );
}
